name: Make the project
run-name: ${{ github.actor }} is building their changes
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Building..."
      - name: Build the project
        steps:
          - name: Install ARM GCC toolchain
            run: |
              sudo apt-get update
              sudo apt-get install -y gcc-arm-none-eabi arm-none-eabi-binutils-cs

          - name: Run build command
            run: make clean && make
      - run: echo "This job's status is ${{ job.status }}."
